[workspace]
members = [ "dys-*" ]

resolver = "2"

# Ensure we're optimizing Rapier (physics) always in dev builds
[profile.dev.package.rapier3d]
opt-level = 3

# For smaller + faster WASM artifacts: https://bevy-cheatbook.github.io/platforms/wasm/size-opt.html#link-time-optimization-lto
[profile.release.package.dys-matchvisualizer]
opt-level = "z"

[workspace.dependencies]
# -----------------------
# Build dependencies
# -----------------------
build-deps = "0.1.4"
tonic-build = "0.12"

# -----------------------
# Dev dependencies
# -----------------------
criterion = "0.5.1"

# -----------------------
# Runtime dependencies
# -----------------------
ahash = "0.8"
axum = "0.7.5"
bevy = { version = "0.15.2", features = ["bevy_asset", "bevy_color", "bevy_core_pipeline", "bevy_render", "bevy_sprite", "bevy_state", "bevy_text", "default_font"] }
crossbeam = "0.8.4"
dyn-clone = "1.0"
eframe = "0.31"
egui = "0.31"
indexmap = "2.7"
once_cell = "1.19.0"
opentelemetry = "0.24"
opentelemetry-http = "0.13"
opentelemetry-otlp = "0.17"
opentelemetry_sdk = { version = "0.24.1", features = ["trace", "metrics", "logs", "rt-tokio"] }
ordered-float = "4.2.0"
petgraph = "0.6.5"
postcard = { version = "1.0.8", features = ["alloc"] }
prost = { version = "0.13.5", features = ["prost-derive"] }
rand = "0.8.5"
rand_distr = "0.4.3"
rand_pcg = "0.3.1"
rapier3d = { version = "0.23.0", features = ["serde-serialize", "enhanced-determinism"] }
redis = { version = "0.28.2", features = ["tokio-rustls-comp"] }
reqwest = { version = "0.12.12", default-features = false, features = ["charset", "http2", "rustls-tls"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0.120" }
strum = { version = "0.26" }
strum_macros = { version = "0.26" }
tokio = { version = "1.40", features = ["full"] }
tonic = "0.12"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.5.2", features = ["fs", "trace"] }
tracing = { version = "0.1.40", features = ["attributes", "log"] }
tracing-bunyan-formatter = "0.3"
tracing-opentelemetry = "0.25"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "json"] }
wasm-bindgen = "0.2.100"
web-time = "1.1.0"