[workspace]
members = [ "dys-*" ]

resolver = "2"

[workspace.dependencies]
tonic-build = "0.11" # Build dependency only!

tonic = "0.11"
prost = "0.12"
tokio = { version = "1.36", features = ["full"] }
serde = "1.0"
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
rand = "0.8.5"