receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: "nats"
          scrape_interval: 15s
          scrape_timeout: 10s
          static_configs:
            - targets: ["nats-exporter:7777"]

processors:
  batch:
    send_batch_size: 10000
    timeout: 5s
  metricstransform:
    transforms:
      # Prepend "dax_dev_" to all metrics
      - include: ^(.*)$$
        match_type: regexp
        action: update
        new_name: dax_dev_$${1}

exporters:
  otlphttp/openobserve:
    endpoint: _ENDPOINT_
    headers:
      Authorization: Basic _AUTH_
      organization: default
      stream-name: _STREAM_

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, metricstransform]
      exporters: [otlphttp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]
