apiVersion: apps/v1
kind: Deployment
metadata:
  name: dys-svc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dys-svc-auth
  template:
    metadata:
      labels:
        app: dys-svc-auth
    spec:
      containers:
      - name: dys-svc-auth
        image: dystopiadev.azurecr.io/dys-svc-auth:latest
        ports:
        - containerPort: 6082
          name: http-port
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 75m
            memory: 200Mi
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_ENDPOINT
            value: "http://$(NODE_IP):4317"
          - name: VALKEY_HOST
            value: "valkey-primary.valkey"
          - name: VALKEY_PASS
            valueFrom:
              secretKeyRef:
                name: "valkeypass"
                key: default_password
          - name: NATS_HOST
            value: "nats.nats"
          - name: NATS_TOKEN
            valueFrom:
              secretKeyRef:
                name: "natstoken"
                key: token
        livenessProbe:
          httpGet:
            port: http-port
            path: /health
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: http-port
            path: /health
          failureThreshold: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: dys-svc-auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 6082
  selector:
    app: dys-svc-auth