apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dax
spec:
  secretName: {{ .Values.tlsSecret }}
  privateKey:
    rotationPolicy: Always
  commonName: {{ .Values.fqdn }}
  dnsNames:
    - {{ .Values.fqdn }}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer