apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: certmanager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certRegistrationEmailAddress }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          azureDNS:
            resourceGroupName: {{ .Values.aks.resourceGroupName }}
            subscriptionID: {{ .Values.aks.subscriptionId }}
            hostedZoneName: {{ .Values.aks.zoneName }}
            environment: AzurePublicCloud
            managedIdentity:
              clientID: {{ .Values.aks.userClientId }}
