apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dax
spec:
  secretName: $TLS_SECRET
  privateKey:
    rotationPolicy: Always
  commonName: $FQDN
  dnsNames:
    - $FQDN
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer