apiVersion: apps/v1
kind: Deployment
metadata:
  name: dys-svc-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dys-svc-webapp
  template:
    metadata:
      labels:
        app: dys-svc-webapp
    spec:
      containers:
      - name: dys-svc-webapp
        image: dystopiadev.azurecr.io/dys-svc-webapp:latest
        ports:
        - containerPort: 6080
          name: http-port
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        env:
          - name: SVC_DIRECTOR_API_BASE_URI
            value: "http://dys-svc-director"
          - name: OTEL_ENDPOINT
            value: "http://alloy.grafana-alloy:4317"
        livenessProbe:
          httpGet:
            port: http-port
            path: /health
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: http-port
            path: /health
          failureThreshold: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dys-svc-webapp
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 6080
  selector:
    app: dys-svc-webapp