services:
  director:
    container_name: "director"
    build:
      context: ..
      dockerfile: ./dys-svc-director/Dockerfile
    environment:
      - OTEL_ENDPOINT=http://otel-collector:4317
      - RUST_BACKTRACE=1
    ports:
      - "6081:6081"
    depends_on:
      valkey:
        condition: service_started
  webapp:
    container_name: "webapp"
    build:
      context: ..
      dockerfile: ./dys-svc-webapp/Dockerfile
    environment:
      - SVC_DIRECTOR_API_BASE_URI=http://director:6081
      - SVC_AUTH_API_BASE_URI=http://auth:6082
      - OTEL_ENDPOINT=http://otel-collector:4317
      - RUST_BACKTRACE=1
    ports:
      - "6080:6080"
    depends_on:
      valkey:
        condition: service_started
  auth:
    container_name: "auth"
    build:
      context: ..
      dockerfile: ./dys-svc-auth/Dockerfile
    environment:
      - OTEL_ENDPOINT=http://otel-collector:4317
      - RUST_BACKTRACE=1
    ports:
      - "6082:6082"
    depends_on:
      valkey:
        condition: service_started
  # ZJ-TODO: remove
  openobserve:
    container_name: "openobserve"
    image: "public.ecr.aws/zinclabs/openobserve:latest"
    environment:
      - ZO_ROOT_USER_EMAIL=dax@determinism.dev
      - ZO_ROOT_USER_PASSWORD=local-dev
    ports:
      - "5080:5080"
      - "5082:5082"
      - "5514:5514/tcp"
      - "5514:5514/udp"
  # ZJ-TODO: remove
  get-openobserve-secret:
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - |
        apk add --no-cache curl jq
        sleep 3
        ACCESS_TOKEN=$(echo "dax@determinism.dev:local-dev" | base64)
        OPENOBSERVE_SECRET=$(curl -s -H "Cookie: auth_tokens={\"access_token\":\"Basic $$ACCESS_TOKEN\",\"refresh_token\":\"\"}" http://172.18.0.1:5080/api/default/passcode | jq '.data.passcode' | tr -d '\"')
        BASIC_AUTH_TOKEN=$(echo "dax@determinism.dev:$$OPENOBSERVE_SECRET" | base64)
        sed -E "s/Authorization: Basic ([a-zA-Z0-9\+\/=]+)/Authorization: Basic $$BASIC_AUTH_TOKEN/g" /opt/otel-collector.yaml > /opt/otel-config/config.yaml
    volumes:
      - ./config/otel-collector.yaml:/opt/otel-collector.yaml
      - otelcollector:/opt/otel-config
    depends_on:
      openobserve:
        condition: service_started
  otel-collector:
    container_name: "otel-collector"
    image: "otel/opentelemetry-collector-contrib:0.121.0"
    ports:
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    depends_on:
      get-openobserve-secret:
        condition: service_completed_successfully
    volumes:
      - otelcollector:/etc/otelcol-contrib
  # ZJ-TODO: remove
  valkey:
    container_name: "valkey"
    image: "valkey/valkey"
    ports:
      - "6379:6379"
  # ZJ-TODO: remove
  redis-insight:
    container_name: "redis-insight"
    image: "redis/redisinsight"
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
  nats:
    container_name: "nats"
    image: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--auth"
      - "replaceme"
      - "-m"
      - "8222"
  cloudflared:
    container_name: "cloudflared"
    image: "cloudflare/cloudflared"
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
      - "--url"
      - "http://localhost:6080"
      - "--token"
      - "${CLOUDFLARED_TOKEN}"
volumes:
  redisinsight:
  otelcollector: