services:
  director:
    container_name: "director"
    build:
      context: ..
      dockerfile: ./dys-svc-director/Dockerfile
    environment:
      - OTEL_ENDPOINT=http://otel-collector:4317
      - RUST_BACKTRACE=1
    ports:
      - "6081:6081"
    depends_on:
      valkey:
        condition: service_started
  webapp:
    container_name: "webapp"
    build:
      context: ..
      dockerfile: ./dys-svc-webapp/Dockerfile
    environment:
      - SVC_DIRECTOR_API_BASE_URI=http://director:6081
      - SVC_AUTH_API_BASE_URI=http://auth:6082
      - OTEL_ENDPOINT=http://otel-collector:4317
      - RUST_BACKTRACE=1
    ports:
      - "6080:6080"
    depends_on:
      valkey:
        condition: service_started
  auth:
    container_name: "auth"
    build:
      context: ..
      dockerfile: ./dys-svc-auth/Dockerfile
    environment:
      - OTEL_ENDPOINT=http://otel-collector:4317
      - RUST_BACKTRACE=1
    ports:
      - "6082:6082"
    depends_on:
      valkey:
        condition: service_started
  get-openobserve-secret:
    image: alpine
    command:
      - "/bin/sh"
      - "-c"
      - |
        sed -E "s/endpoint: (_ENDPOINT_)/endpoint: $$OPENOBSERVE_API_ENDPOINT/g" /opt/otel-collector.yaml > /opt/otel-collector.tmp.yaml
        sed -E "s/Authorization: Basic (_AUTH_)/Authorization: Basic $$OPENOBSERVE_BASIC_AUTH_TOKEN/g" /opt/otel-collector.tmp.yaml > /opt/otel-config/config.yaml
        cat /opt/otel-config/config.yaml
    volumes:
      - ./config/otel-collector.yaml:/opt/otel-collector.yaml
      - otelcollector:/opt/otel-config
  otel-collector:
    container_name: "otel-collector"
    image: "otel/opentelemetry-collector-contrib:0.121.0"
    ports:
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    depends_on:
      get-openobserve-secret:
        condition: service_completed_successfully
    volumes:
      - otelcollector:/etc/otelcol-contrib
  # ZJ-TODO: remove
  valkey:
    container_name: "valkey"
    image: "valkey/valkey"
    ports:
      - "6379:6379"
  # ZJ-TODO: remove
  redis-insight:
    container_name: "redis-insight"
    image: "redis/redisinsight"
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
  nats:
    container_name: "nats"
    image: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--auth"
      - "replaceme"
      - "-m"
      - "8222"
  cloudflared:
    container_name: "cloudflared"
    image: "cloudflare/cloudflared"
    command:
      - "tunnel"
      - "--no-autoupdate"
      - "run"
      - "--url"
      - "http://webapp:6080"
      - "--token"
      - "${CLOUDFLARED_TOKEN}"
volumes:
  redisinsight:
  otelcollector: