services:
  director:  
    container_name: "director"
    build:
      context: ..
      dockerfile: ./dys-svc-director/Dockerfile
    environment:
      - OTEL_ENDPOINT=http://jaeger:4317
      - RUST_BACKTRACE=1
    ports:
      - "6081:6081"
    depends_on:
      valkey:
        condition: service_started
  webapp:
    container_name: "webapp"
    build:
      context: ..
      dockerfile: ./dys-svc-webapp/Dockerfile
    environment:
      - SVC_DIRECTOR_API_BASE_URI=http://director:6081
      - OTEL_ENDPOINT=http://jaeger:4317
      - RUST_BACKTRACE=1
    ports:
      - "6080:6080"
    depends_on:
      valkey:
        condition: service_started
  webapp-hot-reload:
    container_name: "webapp-frontend-hot-reload"
    build:
      context: ..
      dockerfile: ./dys-svc-webapp/Frontend.Dockerfile
    environment:
      - SVC_DIRECTOR_API_BASE_URI=http://director:6081
      - OTEL_ENDPOINT=http://jaeger:4317
      - RUST_BACKTRACE=1
    develop:
      watch:
        - action: sync
          path: ../dys-svc-webapp/frontend
          target: /frontend
          ignore:
            - node_modules/
    ports:
      - "5173:5173"
      - "5174:5174"
    depends_on:
      valkey:
        condition: service_started
  jaeger:
    container_name: "jaeger"
    image: "jaegertracing/all-in-one:1.61.0"
    entrypoint: /go/bin/all-in-one-linux --log-level=warn
    ports:
      - "6831:6831/udp" # agent: Thrift-compact protocol
      - "6832:6832/udp" # agent: Thrift-binary protocol
      - "5775:5775" # agent: deprecated
      - "5778:5778" # agent: serve configs
      - "16686:16686" # query: serve HTTP frontend
      - "4317:4317" # collector: OTLP over gRPC
      - "4318:4318" # collector: OTLP over HTTP
      - "14268:14268" # collector: thrift directly from clients
      - "14250:14250" # collector: model.proto
      - "9411:9411" # collector: optional Zipkin endpoint
  valkey:
    container_name: "valkey"
    image: "valkey/valkey"
    ports:
      - "6379:6379"
  redis-insight:
    container_name: "redis-insight"
    image: "redis/redisinsight"
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
  nats:
    container_name: "nats"
    image: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command:
      - "--auth"
      - "replaceme"
      - "-m"
      - "8222"
volumes:
  redisinsight: