services:
  director:  
    container_name: "director"
    build:
      context: ..
      dockerfile: docker/dys-svc-director.Dockerfile
    environment:
      - OTEL_ENDPOINT=http://jaeger:4317
    ports:
      - "6081:6081"
  webapp:
    container_name: "webapp"
    build:
      context: ..
      dockerfile: docker/dys-svc-webapp.Dockerfile
      #args:
      #  BIN_CMD: "npm run dev"
      #  INSTALL_NPM: "true"
    environment:
      - SVC_DIRECTOR_API_BASE_URI=http://director:6081
      - OTEL_ENDPOINT=http://jaeger:4317
    ports:
      - "6080:6080"
      #- "5173:5173"
  jaeger:
    container_name: "jaeger"
    image: "jaegertracing/all-in-one:1.61.0"
    entrypoint: /go/bin/all-in-one-linux --log-level=warn
    ports:
      - "6831:6831/udp" # agent: Thrift-compact protocol
      - "6832:6832/udp" # agent: Thrift-binary protocol
      - "5775:5775" # agent: deprecated
      - "5778:5778" # agent: serve configs
      - "16686:16686" # query: serve HTTP frontend
      - "4317:4317" # collector: OTLP over gRPC
      - "4318:4318" # collector: OTLP over HTTP
      - "14268:14268" # collector: thrift directly from clients
      - "14250:14250" # collector: model.proto
      - "9411:9411" # collector: optional Zipkin endpoint
  valkey:
    container_name: "valkey"
    image: "valkey/valkey"
    ports:
      - "6379:6379"