[package]
name = "dys-satisfiable-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
dys-satisfiable = { path = "../dys-satisfiable" }

dyn-clone.workspace = true
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"