[package]
name = "dys-protocol"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tonic-build.workspace = true
walkdir = "2.5.0"

[dependencies]
prost.workspace = true
serde.workspace = true
tonic.workspace = true