[package]
name = "dys-svc-director"
version = "0.1.0"
edition = "2021"

[dependencies]
dys-game = { path = "../dys-game" }
dys-world = { path = "../dys-world" }

axum.workspace = true
postcard.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-bunyan-formatter.workspace = true
tracing-subscriber.workspace = true