[package]
name = "dys-matchvisualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
dys-game = { path = "../dys-simulation" }

bevy.workspace = true
once_cell.workspace = true
postcard.workspace = true
serde.workspace = true
wasm-bindgen.workspace = true
web-time.workspace = true