name: dystopia-game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build prereqs
      run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev protobuf-compiler
    - name: Cache build
      uses: actions/cache@v4.2.3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --release --verbose

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Install build prereqs
        run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev protobuf-compiler
      - name: Load cached build
        uses: actions/cache/restore@v4.2.3
        with:
          path: target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test --release --verbose

  benchmarks:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Install build prereqs
      run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev protobuf-compiler
    - name: Load cached build
      uses: actions/cache/restore@v4.2.3
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#    - name: Load latest benchmark artifacts
#      uses: actions/download-artifact@v4
#      with:
#        name: bench-latest
#        path: target/criterion/
#        merge-multiple: true
    - name: Run benchmarks
      run: cargo bench
    - name: Upload bench artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bench-latest
        path: target/criterion/
        overwrite: true
      # ZJ-TODO: alert on major regression?
      # ZJ-TODO: post report somewhere to be web accessible
