name: dystopia-game

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install build prereqs
      run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev protobuf-compiler
    - name: Cache build
      uses: actions/cache@v4.2.3
      with:
        path: |
          dys-protocol/generated/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-
    - name: Build
      run: cargo build --release --verbose

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Install build prereqs
        run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev protobuf-compiler
      - name: Load cached build
        uses: actions/cache@v4.2.3
        with:
          path: |
            dys-protocol/generated/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
            ${{ runner.os }}-cargo-
      - name: Run tests
        run: cargo test --release --verbose

  benchmarks:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Install build prereqs
      run: sudo apt-get install -yqq pkg-config libx11-dev libasound2-dev libudev-dev protobuf-compiler
    - name: Load cached build
      uses: actions/cache@v4.2.3
      with:
        path: |
          dys-protocol/generated/
          target/
        key: ${{ runner.os }}-cargo-benchmark-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-cargo-benchmark-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-
    - name: Run benchmarks
      run: cargo bench
      # ZJ-TODO: alert on major regression?
      # ZJ-TODO: post report somewhere to be web accessible
